version: "3.8"

services:
  frontend:
    image: nginx:alpine
    container_name: nginx-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    # Nginx-ga bosh sahifa sifatida nexus.html-ni o'qishni buyuramiz:
    command: [ "nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf" ]
    # Muqobil va eng kafolatlangan yo'li: pastdagi buyruq orqali index faylini ko'rsatamiz:
    entrypoint: >
      /bin/sh -c "sed -i 's/index  index.html index.htm;/index  nexus.html index.html index.htm;/' /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    restart: always

  backend:
    image: eclipse-temurin:17-jdk
    container_name: spring-backend
    ports:
      - "8080:8080"
    volumes:
      - ./build/libs:/app
    working_dir: /app
    command: java -jar Networking-0.0.1-SNAPSHOT.jar
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hotel_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"