version: "3.8"

services:
  frontend:
    image: nginx:alpine
    container_name: nginx-frontend
    ports:
      - "80:80"
    volumes:
      # Fayl ildizda turgani uchun ./frontend yozuvi mutlaqo to'g'ri!
      - ./frontend:/usr/share/nginx/html
    restart: always

  backend:
    image: eclipse-temurin:17-jdk
    container_name: spring-backend
    ports:
      - "8080:8080"
    volumes:
      - ./build/libs:/app
    working_dir: /app
    command: java -jar Networking-0.0.1-SNAPSHOT.jar
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hotel_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"