version: "3.8"

services:
  frontend:
    build:
      context: ./frontend   # Endi u uzoqqa bormaydi, shu loyiha ichidagi frontend papkasini oladi
      dockerfile: Dockerfile
    container_name: nginx-frontend
    ports:
      - "80:80"             # Global HTTP so'rovlarni qabul qiladi
    restart: always
    depends_on:
      - backend

  backend:
    build: .
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hotel_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"