spring.datasource.url=jdbc:postgresql://localhost:5432/people
spring.datasource.username=postgres
spring.datasource.password=nietbek1
spring.jpa.hibernate.ddl-auto=update
server.port=8080

spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS